name: Jekyll Bulma Github pages starter template
markdown: kramdown

permalink: /blog/:year/:month/:day/:title

site.title: Jekyll Bulma Starter Template

site.base_url: "https://mmoi.github.io/jekyll-bulma-starter/"
